dependencies:
- name: bedrock-k8s-anoop
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.1
- name: bedrock-k8s-pranshu
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.3
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
